# console:
#   address: 0.0.0.0
#   max_message_size_bytes:
#   idle_timeout_ms:
#   password: password
#   port: 7351
#   read_timeout_ms:
#   signing_key:
#   token_expiry_sec: 86400
#   username: admin
#   write_timeout_ms:
# data_dir: ./data/
database:
  address:
    - root@cockroach:26257/nakama
  # conn_max_lifetime_ms: 0
  # dns_scan_interval_sec: 60
  # max_idle_conns: 100
  # max_open_conns: 0
# leaderboard:
#   blacklist_rank_cache:
#   callback_queue_size: 65536
#   callback_queue_workers: 8
logger:
  # compress: gzip
  # file: /nakama/data/logfile.log
  # format: json
  level: debug
  # local_time:
  # max_age:
  # max_backups:
  # max_size:
  # rotation: false
  # stdout: true
# match:
#   call_queue_size: 128
#   deferred_queue_size: 128
#   input_queue_size: 128
#   join_attempt_queue_size: 128
#   join_marker_deadline_ms: 5000
#   label_update_interval_ms: 1000
#   max_empty_sec: 0
metrics:
  # namespace:
  # prefix: nakama
  prometheus_port: 9100
  # reporting_freq_sec: 60
name: nakama-node-1
# runtime:
#   call_stack_size: 128
#   env: key1=value1;key2=value2
#   event_queue_size: 65536
#   event_queue_workers: 8
#   http_key: defaulthttpkey
#   js_entrypoint:
#   js_max_count: 32
#   js_min_count: 16
#   js_read_only_globals: true
#   lua_call_stack_size: 128
#   lua_max_count: 48
#   lua_min_count: 16
#   lua_read_only_globals: true
#   lua_api_stacktrace: true
#   lua_registry_size: 512
#   max_count: 256
#   min_count: 16
#   path: data_dir/modules
#   read_only_globals: true
#   registry_size: 512
# session:
#   encryption_key: defaultencryptionkey
#   refresh_encryption_key: defaultrefreshencryptionkey
#   refresh_token_expiry_sec: 3600
#   single_match: false
#   single_socket: false
#   token_expiry_sec: 60
# shutdown_grace_sec: 0
# socket:
#   address: 0.0.0.0
#   idle_timeout_ms: 60000
#   max_message_size_bytes: 4096
#   max_request_size_bytes: 4096
#   outgoing_queue_size: 16
#   ping_backoff_threshold: 20
#   ping_period_ms: 15000
#   pong_wait_ms: 25000
#   port: 7350
#   protocol: tcp
#   read_buffer_size_bytes: 4096
#   read_timeout_ms: 10000
#   server_key: defaultkey
#   ssl_certificate:
#   ssl_private_key:
#   write_buffer_size_bytes: 4096
#   write_timeout_ms: 10000
#   write_wait_ms: 5000
# tracker:
#   event_queue_size: 1024
# matchmaker:
#   batch_pool_size: 32
#   max_tickets: 3
#   interval_sec: 15
#   max_intervals: 2
